### PR TITLE
feat: implement some common rules 

### PR DESCRIPTION
**Pull request by ComradeProgrammer**
feat: implement rules 2-6

This pr is supposed to be merged after #11

### CODE REVIEW

**Comment by hsluoyz** [comment]
@ComradeProgrammer plz don't create another PR, in which 2 of all 3 commits are the same with another ongoing PR: https://github.com/casbin/k8s-gatekeeper/pull/11 . If you are creating an "orthogonal" PR and wants to get parallel code review, make sure it contains all "new" commits, which are not contained in the old PR.

image

image

**Comment by hsluoyz** [comment]
@ComradeProgrammer plz rebase the code

**Comment by hsluoyz** [comment]
@sagilio plz review

**Review by sagilio — APPROVED** [review]
LGTM

**Pull request merged**
